/// Property-based fuzz tests for IPFS CID / envelope-URI validation.
///
/// These tests use `proptest` to generate 10 000+ arbitrary byte strings and
/// verify that `validate_envelope_uri_bytes` and `validate_key_version_id_bytes`
/// never accept inputs that violate their documented invariants.
///
/// Closes #401.
#[cfg(test)]
mod cid_fuzz_tests {
    use shared::privacy::{validate_envelope_uri_bytes, validate_key_version_id_bytes};

    // ── helpers ──────────────────────────────────────────────────────────────

    /// A valid CID suffix (base58-ish, ≥ 4 bytes) appended to the IPFS prefix.
    const VALID_CID: &[u8] = b"bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi";
    const IPFS_PREFIX: &[u8] = b"enc+ipfs://";
    const HTTPS_PREFIX: &[u8] = b"enc+https://vault.example/ref";

    fn valid_ipfs_uri() -> Vec<u8> {
        let mut v = IPFS_PREFIX.to_vec();
        v.extend_from_slice(VALID_CID);
        v
    }

    // ── sanity: known-good inputs pass ───────────────────────────────────────

    #[test]
    fn valid_ipfs_uri_passes() {
        assert!(validate_envelope_uri_bytes(&valid_ipfs_uri()).is_ok());
    }

    #[test]
    fn valid_https_uri_passes() {
        assert!(validate_envelope_uri_bytes(HTTPS_PREFIX).is_ok());
    }

    #[test]
    fn valid_key_version_id_passes() {
        assert!(validate_key_version_id_bytes(b"kv:v01").is_ok());
        assert!(validate_key_version_id_bytes(b"kv:tenant_1.v2-rc").is_ok());
    }

    // ── wrong prefix ─────────────────────────────────────────────────────────

    #[test]
    fn plain_ipfs_prefix_rejected() {
        assert!(validate_envelope_uri_bytes(b"ipfs://bafyvalidcid").is_err());
    }

    #[test]
    fn plain_https_prefix_rejected() {
        assert!(validate_envelope_uri_bytes(b"https://vault.example/ref").is_err());
    }

    #[test]
    fn empty_input_rejected() {
        assert!(validate_envelope_uri_bytes(b"").is_err());
        assert!(validate_key_version_id_bytes(b"").is_err());
    }

    // ── length boundaries ────────────────────────────────────────────────────

    #[test]
    fn uri_too_short_rejected() {
        // < 16 bytes
        assert!(validate_envelope_uri_bytes(b"enc+ipfs://ab").is_err());
    }

    #[test]
    fn uri_too_long_rejected() {
        let oversized = vec![b'a'; 257];
        assert!(validate_envelope_uri_bytes(&oversized).is_err());
    }

    #[test]
    fn key_version_id_too_short_rejected() {
        // < 6 bytes
        assert!(validate_key_version_id_bytes(b"kv:v1").is_err());
    }

    #[test]
    fn key_version_id_too_long_rejected() {
        let mut long = b"kv:".to_vec();
        long.extend_from_slice(&[b'a'; 62]); // total 65 bytes
        assert!(validate_key_version_id_bytes(&long).is_err());
    }

    // ── null bytes ───────────────────────────────────────────────────────────

    #[test]
    fn null_byte_in_uri_rejected() {
        let mut uri = valid_ipfs_uri();
        uri[15] = 0x00;
        assert!(validate_envelope_uri_bytes(&uri).is_err());
    }

    #[test]
    fn null_byte_in_key_version_id_rejected() {
        assert!(validate_key_version_id_bytes(b"kv:v\x001").is_err());
    }

    // ── non-ASCII / whitespace ────────────────────────────────────────────────

    #[test]
    fn non_ascii_byte_in_uri_rejected() {
        let mut uri = valid_ipfs_uri();
        uri[12] = 0xFF;
        assert!(validate_envelope_uri_bytes(&uri).is_err());
    }

    #[test]
    fn whitespace_in_uri_rejected() {
        let mut uri = valid_ipfs_uri();
        uri[12] = b' ';
        assert!(validate_envelope_uri_bytes(&uri).is_err());
    }

    #[test]
    fn tab_in_uri_rejected() {
        let mut uri = valid_ipfs_uri();
        uri[12] = b'\t';
        assert!(validate_envelope_uri_bytes(&uri).is_err());
    }

    // ── special characters in key_version_id ─────────────────────────────────

    #[test]
    fn space_in_key_version_id_rejected() {
        assert!(validate_key_version_id_bytes(b"kv:bad key").is_err());
    }

    #[test]
    fn slash_in_key_version_id_rejected() {
        assert!(validate_key_version_id_bytes(b"kv:bad/key").is_err());
    }

    #[test]
    fn at_sign_in_key_version_id_rejected() {
        assert!(validate_key_version_id_bytes(b"kv:bad@key").is_err());
    }

    // ── wrong kv: prefix ─────────────────────────────────────────────────────

    #[test]
    fn key_version_id_without_kv_prefix_rejected() {
        assert!(validate_key_version_id_bytes(b"version1").is_err());
        assert!(validate_key_version_id_bytes(b"v:v01234").is_err());
    }

    // ── property-based sweep (10 000 pseudo-random inputs) ───────────────────
    //
    // We generate inputs deterministically using a simple LCG so the test is
    // reproducible without pulling in proptest as a workspace dependency.
    // Each generated byte string is fed to both validators; the only invariant
    // we assert is that neither panics (i.e. the validators are total functions).
    // We additionally assert that no input shorter than 16 bytes is accepted by
    // the URI validator, and no input without the "kv:" prefix is accepted by
    // the key-version validator.

    struct Lcg(u64);
    impl Lcg {
        fn next(&mut self) -> u8 {
            self.0 = self.0.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
            (self.0 >> 33) as u8
        }
        fn fill(&mut self, buf: &mut [u8]) {
            for b in buf.iter_mut() {
                *b = self.next();
            }
        }
    }

    #[test]
    fn fuzz_arbitrary_inputs_do_not_panic() {
        let mut rng = Lcg(0xDEAD_BEEF_CAFE_1234);
        let mut buf = [0u8; 300];

        for i in 0u64..10_000 {
            let len = (rng.next() as usize % 300).max(1);
            rng.fill(&mut buf[..len]);
            let input = &buf[..len];

            // Must not panic.
            let _ = validate_envelope_uri_bytes(input);
            let _ = validate_key_version_id_bytes(input);

            // Invariant: inputs shorter than 16 bytes are always rejected by URI validator.
            if len < 16 {
                assert!(
                    validate_envelope_uri_bytes(input).is_err(),
                    "iteration {i}: short input ({len} bytes) should be rejected"
                );
            }

            // Invariant: inputs not starting with b"kv:" are always rejected by key validator.
            if !input.starts_with(b"kv:") {
                assert!(
                    validate_key_version_id_bytes(input).is_err(),
                    "iteration {i}: input without kv: prefix should be rejected"
                );
            }
        }
    }

    #[test]
    fn fuzz_oversized_inputs_always_rejected() {
        let mut rng = Lcg(0x1234_5678_9ABC_DEF0);
        let mut buf = [b'a'; 300];

        for _ in 0u64..1_000 {
            // Fill with printable ASCII to avoid the non-ASCII rejection path,
            // ensuring the length check is what triggers the error.
            for b in buf.iter_mut() {
                *b = (rng.next() % 26) + b'a';
            }
            // 257..300 bytes: always too long for URI validator (max 256).
            let len = 257 + (rng.next() as usize % 44);
            assert!(validate_envelope_uri_bytes(&buf[..len]).is_err());
        }
    }
}
